"""Categorized index of GUI modules for navigation and maintenance."""

GUI_MODULE_CATEGORIES = {
    # Public categorized facades introduced to reduce monolithic imports.
    "controls": [
        "controls/control_panel_animation",
        "controls/control_panel_interactions",
        "controls/control_panel_logic",
        "controls/control_panel_scroll",
        "controls/control_panel_updates",
        "controls/control_panel_view",
        "controls/manual_step_controller",
        "controls/map_elites_controls",
        "controls/map_loading",
        "controls/match_controls",
        "controls/minimap_controls",
        "controls/path_controls",
        "controls/runtime_flags",
        "controls/sidebar_render_sections",
        "controls/view_navigation",
        "controls/viewport_controls",
        "controls/window_focus",
    ],
    "overlay": [
        "overlay/debug_overlay",
        "overlay/display_diagnostics",
        "overlay/display_lifecycle",
        "overlay/help_overlay",
        "overlay/inventory_display",
        "overlay/inventory_manager",
        "overlay/item_markers",
        "overlay/status_display",
        "overlay/toast_messages",
        "overlay/toast_notification",
    ],
    "services": [
        "services/auto_solve_execution",
        "services/auto_step_controller",
        "services/block_push_controls",
        "services/path_analysis",
        "services/path_guaranteed_renderer",
        "services/path_strategies",
        "services/route_io",
        "services/route_payload",
        "services/solver_comparison_runner",
        "services/solver_core_state",
        "services/solver_launching",
        "services/solver_metrics_tooltips",
        "services/solver_prestart_cleanup",
        "services/solver_process_worker",
        "services/solver_recovery",
        "services/solver_request_helpers",
        "services/solver_request_orchestration",
        "services/solver_scheduling",
        "services/solver_start_flow",
        "services/solver_start_logic",
        "services/solver_sync_execution",
        "services/solver_utils",
        "services/solver_worker_bootstrap",
        "services/topology_export",
        "services/topology_helpers",
        "services/topology_precheck",
        "services/watchdog_monitor",
    ],
    "common": [
        "common/bottom_panel",
        "common/constants",
        "common/fallbacks",
        "common/module_catalog",
        "common/preview_startup",
        "common/tier2_components",
        "common/widget_tooltips",
        "common/widgets",
    ],
    # Canonical domain implementations.
    "domain_control_panel": [
        "control_panel/animation",
        "control_panel/interactions",
        "control_panel/logic",
        "control_panel/scroll",
        "control_panel/updates",
        "control_panel/view",
    ],
    "domain_solver": [
        "solver/start_flow",
        "solver/start_logic",
        "solver/sync_execution",
        "solver/scheduling",
        "solver/request_helpers",
        "solver/request_orchestration",
        "solver/launching",
        "solver/worker_bootstrap",
        "solver/process_worker",
        "solver/core_state",
        "solver/recovery",
        "solver/prestart_cleanup",
        "solver/utils",
        "solver/comparison_runner",
        "solver/metrics_tooltips",
    ],
    "domain_rendering": [
        "rendering/helpers",
        "rendering/map_overlays",
        "rendering/sidebar_sections",
        "rendering/bottom_panel",
        "rendering/status_display",
        "rendering/help_overlay",
        "rendering/debug_overlay",
        "rendering/path_guaranteed_renderer",
        "rendering/inventory_display",
    ],
    "domain_runtime": [
        "runtime/flags",
        "runtime/display_lifecycle",
        "runtime/display_diagnostics",
        "runtime/window_focus",
        "runtime/watchdog_monitor",
        "runtime/temp_file_tools",
        "runtime/temp_file_management",
        "runtime/route_payload",
        "runtime/route_io",
        "runtime/toast_messages",
        "runtime/toast_notification",
    ],
    "domain_map": [
        "map/loading",
        "map/navigation",
        "map/viewport",
        "map/minimap",
    ],
    "domain_gameplay": [
        "gameplay/path_analysis",
        "gameplay/path_controls",
        "gameplay/path_strategies",
        "gameplay/inventory_manager",
        "gameplay/item_markers",
        "gameplay/manual_step_controller",
        "gameplay/auto_step_controller",
        "gameplay/auto_solve_execution",
        "gameplay/block_push_controls",
        "gameplay/map_elites_controls",
        "gameplay/preview_startup",
    ],
    "domain_topology": [
        "topology/export",
        "topology/helpers",
        "topology/precheck",
        "topology/match_controls",
    ],
    "domain_components": [
        "components/constants",
        "components/fallbacks",
        "components/widgets",
        "components/tier2_components",
    ],
    "domain_ai": [
        "ai/generation_controls",
        "ai/generation_pipeline",
        "ai/generation_worker",
    ],
}


def list_categories() -> list[str]:
    """Return sorted category names."""
    return sorted(GUI_MODULE_CATEGORIES.keys())
